// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UdemyDiary.Data;

#nullable disable

namespace UdemyDiary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241107124909_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UdemyDiary.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the first entry in the diary.",
                            Created = new DateTime(2024, 11, 7, 12, 49, 9, 192, DateTimeKind.Local).AddTicks(7675),
                            Title = "First Entry"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is the second entry in the diary.",
                            Created = new DateTime(2024, 11, 7, 12, 49, 9, 192, DateTimeKind.Local).AddTicks(7678),
                            Title = "Second Entry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
